/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavesRouteImport } from './routes/saves'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as DocsSpaceSlugRouteImport } from './routes/docs/$space.$slug'
import { Route as SupportCategoryIdIndexRouteImport } from './routes/support/$categoryId/index'
import { Route as SupportCategoryIdSlugRouteImport } from './routes/support/$categoryId/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesRoute = SavesRouteImport.update({
  id: '/saves',
  path: '/saves',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSpaceSlugRoute = DocsSpaceSlugRouteImport.update({
  id: '/docs/$space/$slug',
  path: '/docs/$space/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportCategoryIdIndexRoute = SupportCategoryIdIndexRouteImport.update({
  id: '/support/$categoryId/',
  path: '/support/$categoryId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportCategoryIdSlugRoute = SupportCategoryIdSlugRouteImport.update({
  id: '/support/$categoryId/$slug',
  path: '/support/$categoryId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/saves': typeof SavesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support/': typeof SupportIndexRoute
  '/docs/$space/$slug': typeof DocsSpaceSlugRoute
  '/support/$categoryId/$slug': typeof SupportCategoryIdSlugRoute
  '/support/$categoryId/': typeof SupportCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/saves': typeof SavesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportIndexRoute
  '/docs/$space/$slug': typeof DocsSpaceSlugRoute
  '/support/$categoryId/$slug': typeof SupportCategoryIdSlugRoute
  '/support/$categoryId': typeof SupportCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/saves': typeof SavesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support/': typeof SupportIndexRoute
  '/docs/$space/$slug': typeof DocsSpaceSlugRoute
  '/support/$categoryId/$slug': typeof SupportCategoryIdSlugRoute
  '/support/$categoryId/': typeof SupportCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/saves'
    | '/sitemap.xml'
    | '/support/'
    | '/docs/$space/$slug'
    | '/support/$categoryId/$slug'
    | '/support/$categoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/saves'
    | '/sitemap.xml'
    | '/support'
    | '/docs/$space/$slug'
    | '/support/$categoryId/$slug'
    | '/support/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/saves'
    | '/sitemap.xml'
    | '/support/'
    | '/docs/$space/$slug'
    | '/support/$categoryId/$slug'
    | '/support/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SavesRoute: typeof SavesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportIndexRoute: typeof SupportIndexRoute
  DocsSpaceSlugRoute: typeof DocsSpaceSlugRoute
  SupportCategoryIdSlugRoute: typeof SupportCategoryIdSlugRoute
  SupportCategoryIdIndexRoute: typeof SupportCategoryIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves': {
      id: '/saves'
      path: '/saves'
      fullPath: '/saves'
      preLoaderRoute: typeof SavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$space/$slug': {
      id: '/docs/$space/$slug'
      path: '/docs/$space/$slug'
      fullPath: '/docs/$space/$slug'
      preLoaderRoute: typeof DocsSpaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$categoryId/': {
      id: '/support/$categoryId/'
      path: '/support/$categoryId'
      fullPath: '/support/$categoryId/'
      preLoaderRoute: typeof SupportCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$categoryId/$slug': {
      id: '/support/$categoryId/$slug'
      path: '/support/$categoryId/$slug'
      fullPath: '/support/$categoryId/$slug'
      preLoaderRoute: typeof SupportCategoryIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SavesRoute: SavesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportIndexRoute: SupportIndexRoute,
  DocsSpaceSlugRoute: DocsSpaceSlugRoute,
  SupportCategoryIdSlugRoute: SupportCategoryIdSlugRoute,
  SupportCategoryIdIndexRoute: SupportCategoryIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
