/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnregistrementsRouteImport } from './routes/enregistrements'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as SupportSlugRouteImport } from './routes/support.$slug'
import { Route as DocsSpaceSlugRouteImport } from './routes/docs.$space.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnregistrementsRoute = EnregistrementsRouteImport.update({
  id: '/enregistrements',
  path: '/enregistrements',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportSlugRoute = SupportSlugRouteImport.update({
  id: '/support/$slug',
  path: '/support/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSpaceSlugRoute = DocsSpaceSlugRouteImport.update({
  id: '/docs/$space/$slug',
  path: '/docs/$space/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enregistrements': typeof EnregistrementsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support/$slug': typeof SupportSlugRoute
  '/support/': typeof SupportIndexRoute
  '/docs/$space/$slug': typeof DocsSpaceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enregistrements': typeof EnregistrementsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support/$slug': typeof SupportSlugRoute
  '/support': typeof SupportIndexRoute
  '/docs/$space/$slug': typeof DocsSpaceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enregistrements': typeof EnregistrementsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support/$slug': typeof SupportSlugRoute
  '/support/': typeof SupportIndexRoute
  '/docs/$space/$slug': typeof DocsSpaceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/enregistrements'
    | '/sitemap.xml'
    | '/support/$slug'
    | '/support/'
    | '/docs/$space/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enregistrements'
    | '/sitemap.xml'
    | '/support/$slug'
    | '/support'
    | '/docs/$space/$slug'
  id:
    | '__root__'
    | '/'
    | '/enregistrements'
    | '/sitemap.xml'
    | '/support/$slug'
    | '/support/'
    | '/docs/$space/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnregistrementsRoute: typeof EnregistrementsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportSlugRoute: typeof SupportSlugRoute
  SupportIndexRoute: typeof SupportIndexRoute
  DocsSpaceSlugRoute: typeof DocsSpaceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enregistrements': {
      id: '/enregistrements'
      path: '/enregistrements'
      fullPath: '/enregistrements'
      preLoaderRoute: typeof EnregistrementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$slug': {
      id: '/support/$slug'
      path: '/support/$slug'
      fullPath: '/support/$slug'
      preLoaderRoute: typeof SupportSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$space/$slug': {
      id: '/docs/$space/$slug'
      path: '/docs/$space/$slug'
      fullPath: '/docs/$space/$slug'
      preLoaderRoute: typeof DocsSpaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnregistrementsRoute: EnregistrementsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportSlugRoute: SupportSlugRoute,
  SupportIndexRoute: SupportIndexRoute,
  DocsSpaceSlugRoute: DocsSpaceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
